"""add_store_upi_vpa

Revision ID: 71ff79d17572
Revises: 75d52a2435e5
Create Date: 2026-09-18 10:09:07.291385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ff79d17572'
down_revision: Union[str, None] = '75d52a2435e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('upi_vpa', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'upi_vpa')
    # ### end Alembic commands ###
