"""initial_payflow_schema

Revision ID: 75d52a2435e5
Revises: 
Create Date: 2026-09-18 09:56:48.730284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75d52a2435e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('kyc_status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', name='merchant_kyc_status'), nullable=False),
    sa.Column('upi_vpa', sa.String(length=100), nullable=True),
    sa.Column('mcc_code', sa.String(length=4), nullable=True),
    sa.Column('risk_tier', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'PROHIBITED', name='merchant_risk_tier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchants_email'), 'merchants', ['email'], unique=True)
    op.create_index(op.f('ix_merchants_phone'), 'merchants', ['phone'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_table('webhook_events_inbound',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSED', 'FAILED', 'IGNORED', name='webhook_inbound_status'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('entity_name', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'STATUS_CHANGE', 'REFUND_TRIGGER', name='audit_action'), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_name', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_name'), 'audit_logs', ['entity_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_merchant_id'), 'audit_logs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('upi_vpa', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_merchant_id'), 'customers', ['merchant_id'], unique=False)
    op.create_index('ix_customers_merchant_phone', 'customers', ['merchant_id', 'phone'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_table('merchant_kyc_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('PAN', 'GSTIN', 'INCORPORATION_CERT', 'BANK_STATEMENT', 'AADHAAR', 'OTHER', name='kyc_document_type'), nullable=False),
    sa.Column('document_number', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'VERIFIED', 'REJECTED', name='kyc_document_status'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_kyc_documents_merchant_id'), 'merchant_kyc_documents', ['merchant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.Enum('SMS', 'EMAIL', 'WHATSAPP', 'WEBHOOK', 'IN_APP', name='notification_channel'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'DELIVERED', 'FAILED', name='notification_status'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_merchant_id'), 'notifications', ['merchant_id'], unique=False)
    op.create_table('reconciliation_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('batch_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'MATCHED', 'DISCREPANCIES_FOUND', 'COMPLETED', name='reconciliation_status'), nullable=False),
    sa.Column('total_records', sa.Integer(), nullable=False),
    sa.Column('matched_records', sa.Integer(), nullable=False),
    sa.Column('mismatched_records', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_batches_merchant_id'), 'reconciliation_batches', ['merchant_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('settlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('settlement_cycle', sa.Enum('T_PLUS_0', 'T_PLUS_1', 'T_PLUS_2', 'ON_DEMAND', name='settlement_cycle'), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SETTLED', 'FAILED', name='settlement_status'), nullable=False),
    sa.Column('bank_account_ref', sa.String(length=100), nullable=False),
    sa.Column('payout_ref_id', sa.String(length=100), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlements_merchant_id'), 'settlements', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_settlements_payout_ref_id'), 'settlements', ['payout_ref_id'], unique=False)
    op.create_table('stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'code', name='uq_stores_merchant_code')
    )
    op.create_index(op.f('ix_stores_merchant_id'), 'stores', ['merchant_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', 'merchant_id')
    )
    op.create_index(op.f('ix_user_roles_merchant_id'), 'user_roles', ['merchant_id'], unique=False)
    op.create_table('webhook_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('target_url', sa.String(length=1024), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('subscribed_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_subscriptions_merchant_id'), 'webhook_subscriptions', ['merchant_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED', 'OVERDUE', 'REFUNDED', name='invoice_status'), nullable=False),
    sa.Column('allow_partial_payment', sa.Boolean(), nullable=False),
    sa.Column('allow_split_payment', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'invoice_number', name='uq_invoices_merchant_number')
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_merchant_id'), 'invoices', ['merchant_id'], unique=False)
    op.create_index('ix_invoices_merchant_status', 'invoices', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index(op.f('ix_invoices_store_id'), 'invoices', ['store_id'], unique=False)
    op.create_table('merchant_staff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MANAGER', 'CASHIER', 'ACCOUNTANT', name='merchant_staff_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_staff_merchant_id'), 'merchant_staff', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_staff_store_id'), 'merchant_staff', ['store_id'], unique=False)
    op.create_index(op.f('ix_merchant_staff_user_id'), 'merchant_staff', ['user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', 'RETRYING', name='webhook_delivery_status'), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['webhook_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_deliveries_subscription_id'), 'webhook_deliveries', ['subscription_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_table('payment_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('short_code', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAID', 'EXPIRED', 'CANCELLED', name='payment_link_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('allow_partial', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_links_customer_id'), 'payment_links', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_links_invoice_id'), 'payment_links', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_links_merchant_id'), 'payment_links', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_links_short_code'), 'payment_links', ['short_code'], unique=True)
    op.create_table('payment_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('plan_type', sa.Enum('DEPOSIT', 'INSTALLMENT', 'MILESTONE', 'CUSTOM_SPLIT', name='plan_type'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', 'DEFAULTED', name='payment_plan_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_plans_customer_id'), 'payment_plans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_plans_invoice_id'), 'payment_plans', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_plans_merchant_id'), 'payment_plans', ['merchant_id'], unique=False)
    op.create_table('payment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'EXPIRED', 'CANCELLED', 'FAILED', name='payment_request_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payer_vpa', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_requests_customer_id'), 'payment_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_requests_invoice_id'), 'payment_requests', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_requests_merchant_id'), 'payment_requests', ['merchant_id'], unique=False)
    op.create_index('ix_payment_requests_merchant_status', 'payment_requests', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_payment_requests_status'), 'payment_requests', ['status'], unique=False)
    op.create_table('upi_qr_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('qr_type', sa.Enum('STATIC', 'DYNAMIC', name='qr_type'), nullable=False),
    sa.Column('upi_string', sa.String(length=1024), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'EXPIRED', name='qr_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upi_qr_codes_invoice_id'), 'upi_qr_codes', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_upi_qr_codes_merchant_id'), 'upi_qr_codes', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_upi_qr_codes_store_id'), 'upi_qr_codes', ['store_id'], unique=False)
    op.create_table('payment_plan_installments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_plan_id', sa.UUID(), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', name='installment_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_plan_id'], ['payment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_plan_installments_payment_plan_id'), 'payment_plan_installments', ['payment_plan_id'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('payment_link_id', sa.UUID(), nullable=True),
    sa.Column('upi_qr_id', sa.UUID(), nullable=True),
    sa.Column('installment_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', 'TIMEOUT', 'REFUNDED', 'PARTIALLY_REFUNDED', name='transaction_status'), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI_COLLECT', 'UPI_INTENT', 'UPI_QR', 'CARD', 'NET_BANKING', 'WALLET', name='payment_method'), nullable=False),
    sa.Column('mock_scenario', sa.String(length=50), nullable=True),
    sa.Column('provider_ref_id', sa.String(length=100), nullable=True),
    sa.Column('payer_vpa', sa.String(length=100), nullable=True),
    sa.Column('payee_vpa', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installment_id'], ['payment_plan_installments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payment_link_id'], ['payment_links.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['upi_qr_id'], ['upi_qr_codes.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transactions_customer_id'), 'payment_transactions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_idempotency_key'), 'payment_transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_payment_transactions_installment_id'), 'payment_transactions', ['installment_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_invoice_id'), 'payment_transactions', ['invoice_id'], unique=False)
    op.create_index('ix_payment_transactions_merchant_created', 'payment_transactions', ['merchant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_payment_transactions_merchant_id'), 'payment_transactions', ['merchant_id'], unique=False)
    op.create_index('ix_payment_transactions_merchant_status', 'payment_transactions', ['merchant_id', 'status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_payment_link_id'), 'payment_transactions', ['payment_link_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_provider_ref_id'), 'payment_transactions', ['provider_ref_id'], unique=False)
    op.create_index(op.f('ix_payment_transactions_status'), 'payment_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_payment_transactions_upi_qr_id'), 'payment_transactions', ['upi_qr_id'], unique=False)
    op.create_table('duplicate_transaction_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('original_transaction_id', sa.UUID(), nullable=False),
    sa.Column('duplicate_transaction_id', sa.UUID(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('flag_reason', sa.Enum('IDENTICAL_IDEMPOTENCY_KEY', 'IDENTICAL_AMOUNT_AND_VPA', 'TIMEFRAME_BURST', 'PROVIDER_RRN_COLLISION', name='duplicate_flag_reason'), nullable=False),
    sa.Column('status', sa.Enum('SUSPECTED', 'CONFIRMED_DUPLICATE', 'FALSE_POSITIVE', 'RESOLVED', name='duplicate_flag_status'), nullable=False),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['duplicate_transaction_id'], ['payment_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_transaction_id'], ['payment_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duplicate_transaction_flags_duplicate_transaction_id'), 'duplicate_transaction_flags', ['duplicate_transaction_id'], unique=False)
    op.create_index(op.f('ix_duplicate_transaction_flags_merchant_id'), 'duplicate_transaction_flags', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_duplicate_transaction_flags_original_transaction_id'), 'duplicate_transaction_flags', ['original_transaction_id'], unique=False)
    op.create_table('reconciliation_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('provider_ref_id', sa.String(length=100), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('MATCHED', 'AMOUNT_MISMATCH', 'STATUS_MISMATCH', 'MISSING_IN_INTERNAL', 'MISSING_IN_PROVIDER', name='reconciliation_entry_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['reconciliation_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_entries_batch_id'), 'reconciliation_entries', ['batch_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_entries_provider_ref_id'), 'reconciliation_entries', ['provider_ref_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_entries_transaction_id'), 'reconciliation_entries', ['transaction_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('INITIATED', 'PENDING', 'SUCCESS', 'FAILED', name='refund_status'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=100), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_merchant_id'), 'refunds', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_refunds_provider_refund_id'), 'refunds', ['provider_refund_id'], unique=False)
    op.create_index(op.f('ix_refunds_transaction_id'), 'refunds', ['transaction_id'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('rule_triggered', sa.String(length=100), nullable=False),
    sa.Column('action_taken', sa.Enum('ALLOW', 'FLAG_FOR_REVIEW', 'CHALLENGE_2FA', 'BLOCK', name='risk_action'), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_merchant_id'), 'risk_signals', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_transaction_id'), 'risk_signals', ['transaction_id'], unique=False)
    op.create_table('settlement_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settlement_line_items_settlement_id'), 'settlement_line_items', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_settlement_line_items_transaction_id'), 'settlement_line_items', ['transaction_id'], unique=False)
    op.create_table('transaction_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_status_history_transaction_id'), 'transaction_status_history', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_status_history_transaction_id'), table_name='transaction_status_history')
    op.drop_table('transaction_status_history')
    op.drop_index(op.f('ix_settlement_line_items_transaction_id'), table_name='settlement_line_items')
    op.drop_index(op.f('ix_settlement_line_items_settlement_id'), table_name='settlement_line_items')
    op.drop_table('settlement_line_items')
    op.drop_index(op.f('ix_risk_signals_transaction_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_merchant_id'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_refunds_transaction_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_provider_refund_id'), table_name='refunds')
    op.drop_index(op.f('ix_refunds_merchant_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_reconciliation_entries_transaction_id'), table_name='reconciliation_entries')
    op.drop_index(op.f('ix_reconciliation_entries_provider_ref_id'), table_name='reconciliation_entries')
    op.drop_index(op.f('ix_reconciliation_entries_batch_id'), table_name='reconciliation_entries')
    op.drop_table('reconciliation_entries')
    op.drop_index(op.f('ix_duplicate_transaction_flags_original_transaction_id'), table_name='duplicate_transaction_flags')
    op.drop_index(op.f('ix_duplicate_transaction_flags_merchant_id'), table_name='duplicate_transaction_flags')
    op.drop_index(op.f('ix_duplicate_transaction_flags_duplicate_transaction_id'), table_name='duplicate_transaction_flags')
    op.drop_table('duplicate_transaction_flags')
    op.drop_index(op.f('ix_payment_transactions_upi_qr_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_status'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_provider_ref_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_payment_link_id'), table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_merchant_status', table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_merchant_id'), table_name='payment_transactions')
    op.drop_index('ix_payment_transactions_merchant_created', table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_invoice_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_installment_id'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_idempotency_key'), table_name='payment_transactions')
    op.drop_index(op.f('ix_payment_transactions_customer_id'), table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index(op.f('ix_payment_plan_installments_payment_plan_id'), table_name='payment_plan_installments')
    op.drop_table('payment_plan_installments')
    op.drop_index(op.f('ix_upi_qr_codes_store_id'), table_name='upi_qr_codes')
    op.drop_index(op.f('ix_upi_qr_codes_merchant_id'), table_name='upi_qr_codes')
    op.drop_index(op.f('ix_upi_qr_codes_invoice_id'), table_name='upi_qr_codes')
    op.drop_table('upi_qr_codes')
    op.drop_index(op.f('ix_payment_requests_status'), table_name='payment_requests')
    op.drop_index('ix_payment_requests_merchant_status', table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_merchant_id'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_invoice_id'), table_name='payment_requests')
    op.drop_index(op.f('ix_payment_requests_customer_id'), table_name='payment_requests')
    op.drop_table('payment_requests')
    op.drop_index(op.f('ix_payment_plans_merchant_id'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_invoice_id'), table_name='payment_plans')
    op.drop_index(op.f('ix_payment_plans_customer_id'), table_name='payment_plans')
    op.drop_table('payment_plans')
    op.drop_index(op.f('ix_payment_links_short_code'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_merchant_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_invoice_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_customer_id'), table_name='payment_links')
    op.drop_table('payment_links')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_webhook_deliveries_subscription_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_merchant_staff_user_id'), table_name='merchant_staff')
    op.drop_index(op.f('ix_merchant_staff_store_id'), table_name='merchant_staff')
    op.drop_index(op.f('ix_merchant_staff_merchant_id'), table_name='merchant_staff')
    op.drop_table('merchant_staff')
    op.drop_index(op.f('ix_invoices_store_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index('ix_invoices_merchant_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_merchant_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_webhook_subscriptions_merchant_id'), table_name='webhook_subscriptions')
    op.drop_table('webhook_subscriptions')
    op.drop_index(op.f('ix_user_roles_merchant_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_stores_merchant_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_settlements_payout_ref_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_merchant_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_reconciliation_batches_merchant_id'), table_name='reconciliation_batches')
    op.drop_table('reconciliation_batches')
    op.drop_index(op.f('ix_notifications_merchant_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_merchant_kyc_documents_merchant_id'), table_name='merchant_kyc_documents')
    op.drop_table('merchant_kyc_documents')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index('ix_customers_merchant_phone', table_name='customers')
    op.drop_index(op.f('ix_customers_merchant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_merchant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('webhook_events_inbound')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_merchants_phone'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_email'), table_name='merchants')
    op.drop_table('merchants')

    # Explicitly drop PostgreSQL named ENUM types on downgrade
    enum_names = [
        'merchant_kyc_status',
        'merchant_risk_tier',
        'kyc_document_type',
        'kyc_document_status',
        'merchant_staff_role',
        'invoice_status',
        'payment_request_status',
        'qr_type',
        'qr_status',
        'payment_link_status',
        'plan_type',
        'payment_plan_status',
        'installment_status',
        'transaction_status',
        'payment_method',
        'webhook_inbound_status',
        'webhook_delivery_status',
        'reconciliation_status',
        'reconciliation_entry_status',
        'duplicate_flag_reason',
        'duplicate_flag_status',
        'refund_status',
        'settlement_cycle',
        'settlement_status',
        'risk_level',
        'risk_action',
        'notification_channel',
        'notification_status',
        'audit_action',
    ]
    for enum_name in enum_names:
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
