import enum
import uuid
from datetime import datetime
from decimal import Decimal
from typing import Optional
from pydantic import BaseModel, ConfigDict, Field

from app.modules.payments.models import TransactionStatus


class MockScenario(str, enum.Enum):
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    PENDING = "PENDING"
    TIMEOUT = "TIMEOUT"
    DUPLICATE = "DUPLICATE"
    PARTIAL_PAYMENT = "PARTIAL_PAYMENT"
    REFUND = "REFUND"


class MockPaymentResult(BaseModel):
    scenario: MockScenario
    status: TransactionStatus
    provider_ref_id: str
    amount: Decimal
    settled_amount: Decimal
    idempotency_key: str
    payer_vpa: str
    failure_reason: Optional[str] = None
    is_async: bool = Field(default=False, description="True if transaction requires async follow-up resolution")
    duplicate_of_transaction_id: Optional[uuid.UUID] = Field(None, description="Original transaction UUID if scenario is DUPLICATE")
    created_at: datetime
    simulator_notice: str = Field(
        default="SIMULATED TRANSACTION - Generated by MockUPIProvider for testing. Not connected to real banking switches.",
        description="Explicit simulator disclaimer"
    )

    model_config = ConfigDict(from_attributes=True)


class SimulatePaymentRequest(BaseModel):
    scenario: Optional[MockScenario] = Field(
        None,
        description="Explicit scenario override (SUCCESS, FAILED, PENDING, TIMEOUT, DUPLICATE, PARTIAL_PAYMENT, REFUND). If omitted, 80% weighted success is applied."
    )


class DirectInitiateRequest(BaseModel):
    amount: Decimal = Field(..., gt=0, description="Transaction payment amount")
    vpa: str = Field(..., description="Target UPI VPA handle")
    idempotency_key: str = Field(..., description="Unique client idempotency token")
    scenario: Optional[MockScenario] = Field(None, description="Optional simulation scenario override")
    merchant_id: Optional[uuid.UUID] = Field(None, description="Optional merchant UUID context")
    invoice_id: Optional[uuid.UUID] = Field(None, description="Optional invoice UUID context")
